---
title: "Minivignette"
author: "Erik"
date: "`r Sys.Date()`"
output: pdf_document
vignette: |
  %\VignetteIndexEntry{Ejemplo de miniviñeta}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Miniviñeta

El objetivo de esta miniviñeta es mostrar ejemplos de cómo se puede usar el paquete.

```{r, include=FALSE}
library(smer)
```


### Creacion de dataset

```{r}
ds2<-dataset(c(3,3,5,8,9,5), id="prueba", factorizar = 5)
ds2
ds2@data$datos
```
```{r}
ds3 <- leer_datos('datos/LecturaCSV_R.csv', encabezado = TRUE, factorizar=6)
ds3
ds3@data$Participante
ds3@data$Conseguido
guardar_datos('datos/Guardado.csv', ds3)

ds3 <- nombres_columna(ds3, c("1", "2", "3", "4"))
ds3 <- nombres_columna(ds3, c("5","6"), c(1,2))
ds3 <- nombres_columna(ds3, 9, 3)
ds3

print(ds3)
```

### Cálculo de métricas

```{r}
vars <- varianzas(ds3)
print(vars)
entr <- entropias(ds3)
print(entr)
entr <- entropias(ds3, discrete=FALSE)
print(entr)
entr <- entropias(ds3, discrete=TRUE,norm=TRUE)
print(entr)
entr <- entropias(ds3, discrete=FALSE,norm=TRUE)
print(entr)
```

```{r}
areasroc(ds3, c(2,2), 4)
#areasroc(ds3, c(4,2), 4) #boolean no
#areasroc(ds3, c(1,2), 4) #factor no
```
```{r}
ds4 <- leer_datos('datos/LecturaCSV_R.csv', encabezado = TRUE, factorizar=2)
#areasroc(ds4, c(3,2), 4) #string no
```
```{r}
co <- correlaciones(ds3)
co
co <- correlaciones(ds4)
co
```
```{r}
infmutuas(ds3)
infmutuas(ds3, logical = TRUE)
```
```{r}
infmutuas(ds4, logical=TRUE)
```

### Discretización

```{r}
discretizar(ds3, 'anchura', 3, 2)
discretizar(ds3, 'frecuencia', 3, 2)
discretizar(ds3, 'manual', c(3,6,8), 2)
```

### Normalización y estandarización

```{r}
normalizar(ds3, 2)
estandarizar(ds3, 2)
```

### Filtrado

```{r}
filtrar(ds3, 1, function(x) x=="5")
filtrar(ds3, 3, function(x) x == "Paula")
filtrar(ds3, 3, function(x) x == "Nerea")
print(filtrar(ds3, 2, function(x) x > 4))
#filtrar(ds3, 3, function(x) x == "Alex")
```

### Gráficos

```{r}
areasroc(ds3, 2, 4, plot=TRUE)
```

```{r}
valoresTrue <- rnorm(100, mean=30, sd=20)
valoresFalse <- rnorm(100, mean=70, sd=20)

etiquetaTrue <- rep(TRUE, 100)
etiquetaFalse <- rep(FALSE, 100)

rocData <- data.frame(variable=c(valoresTrue, valoresFalse), 
                      etiqueta=c(etiquetaTrue, etiquetaFalse))
dsRoc <- dataset(rocData)
areasroc(dsRoc, 1, 2, plot=TRUE)
```


```{r}
entropias(ds3, discrete=TRUE,norm=TRUE, plot=TRUE)
```

```{r}
df2 <- data.frame(first=c(3.2, 5.6, 7.1, 0.9, 8.5),
                 second=c(4.4, 3.1, 1.2, 8.5, 6.3),
                 third=c(4.7, 4.9, 5.3, 1.4, 2.8),
                 fourth=c(0.4, 9.7, 8.6, 0.3, 8.5),
                 fifth=c(3.1, 2.6, 9.8, 7.3, 4.0))
ds5 <- dataset(df2)
correlaciones(ds5, plot=TRUE)
```

```{r}
infmutuas(ds3, logical=TRUE, plot=TRUE)
```


```{r}
graficoBoxplot(ds5)
```

